
* Nome do Software (ou Biblioteca):
- MODELOS DE DESLOCAMENTO IMISCÍVEL PARA RECUPERAÇÃO
SECUNDÁRIA DE PETRÓLEO

* Resumo e/ou informação extra: 
- O projeto a ser desenvolvido consiste em um programa que calculará características
de um reservatório homogêneo a partir de um fluxo bifásico areal, preverá o desempenho
no processo de recuperação secundária do óleo a partir de um sistema estratificado com
fluxo bifásico.
A presente construção do sistema será utilizado em âmbito acadêmico como software
livre, a partir do uso da Programação Orientada a Objeto em C++ e software Gnuplot,
para que esteja disponível de fácil acesso a todos. A interface selecionada para o programa
é em modo texto, o usuário irá se relacionar a partir do uso do teclado, mouse e monitor
em conjunto com a interface do sistema construído. Os dados de entrada, propriedades do
reservatório, serão fornecidos em modo .xlsx, na qual poderá ser modificado pelo usuário
com base nas informações do reservatório em questão, enquanto que os dados de saída
serão em modo arquivo de texto .txt e imagem .png com base nos diferentes modelos de
deslocamento possíveis do software.

* Versão: 
- 1.0.

* Data:
- 2021/2 - segundo semestre.
  
* Autor de Contato:
- André Duarte Bueno <andreduartebueno@gmail.com>

* Lista dos Autores:
- DAVID HENRIQUE LIMA DIAS
- JULIA RANGEL RIBEIRO
- MARCOS VINÍCIUS DE PAULA CHAIBEN
- André Duarte Bueno <andreduartebueno@gmail.com>

* Áreas de pesquisa vinculadas:
- Modelagem Matemática Computacional
- Engenharia de reservatório

* Vinculo com: 
- Trabalho da disciplina de programação prática.

* Paradigmas: 
- POO - Programação Orientada a Objeto (códigos em C++)

* Tipo de Interface: 
- Terminal e gráfica (gnuplot).

* Plataformas Suportadas: 
- Windows e GNU/Linux e Mac OS X (não testada).

* Linguagens Utilizadas: 
- C++ 11.

* Bibliotecas Utilizadas (dependências):
- CGnuplot - https://github.com/ldsc/CGnuplot

* Softwares utilizados (dependências)
- gnuplot http://www.gnuplot.info/

* Tipo de Licença:
- GPL
- Entre em contato com o Prof. André Duarte Bueno
  andreduartebueno@gmail.com
  para que o mesmo gere um novo projeto no github do ldsc para que você (e sua equipe) possam trabalhar na nova versão.
- Se este projeto tem como número de versão 1.0 a nova versão deverá ser 2.0 e assim sucessivamente.
- Os nomes dos autores originais deve ser preservada na nova versão, ou seja, adicione a informação do número da versão, os nomes dos membros da nova equipe, mas jamais apague os nomes dos autores originais (isto seria plágio).
- Na descrição do projeto informe que trata-se de uma nova versão, que tem como base a versão anterior e DESTAQUE COM CLAREZA E OBJETIVIDADE QUAIS AS NOVIDADES DA NOVA VERSÃO.
  
* Links:

